### ISSUE TITLE
'pip install watchdog' fails on OS X 10.10.5

### ISSUE THREAD

**Issue by fx86** [gorakhargosh/watchdog#360]
`pip install watchdog` fails with the following error:

```
src/watchdog_fsevents.c:466:33: warning: unused parameter 'self' [-Wunused-parameter]
    watchdog_remove_watch(PyObject *self, PyObject *watch)
                                    ^
    src/watchdog_fsevents.c:491:25: warning: unused parameter 'self' [-Wunused-parameter]
    watchdog_stop(PyObject *self, PyObject *emitter_thread)
                            ^
    src/watchdog_fsevents.c:531:10: warning: missing field 'ml_meth' initializer [-Wmissing-field-initializers]
        {NULL},
             ^
    8 warnings and 2 errors generated.
    error: command '/usr/bin/clang' failed with exit status 1

    ----------------------------------------
Command "/Users/airborne/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/7c/vvy24k6d483cwl0m6fbl0vdr0000gn/T/pip-build-BozAQp/watchdog/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/7c/vvy24k6d483cwl0m6fbl0vdr0000gn/T/pip-nx7ozu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/7c/vvy24k6d483cwl0m6fbl0vdr0000gn/T/pip-build-BozAQp/watchdog/
```

Can anyone please help out with resolving this error ?
Complete error log is here http://pastebin.com/D2qq9tb1
Python version : Python 2.7.11 |Anaconda 2.4.1 (x86_64)

EDIT: Solutions suggested in a previous bug raised against OSX 10.9 did not seem to work - https://github.com/gorakhargosh/watchdog/issues/224

**Comment by metaljoe** [comment]
I get 9 warnings on OS X 10.10.5, however clang doesn't fail so watchdog is installed. This is with system Python (2.7.11), and tested again with homebrew installed Python3 and PyPy. Apple LLVM 7.0.2 (clang-700.1.81)

**Comment by BoboTiG** [comment]
Fixed with #467.

**Comment by rokcarl** [comment]
I still get the `error: command 'clang' failed with exit status 1`, here's my [entire output](https://gist.github.com/rokcarl/3f3529f4ae21a2dd4819ca10d5ee9e8f) of running `pip install watchdog`.
